### PR TITLE
Fixed #23.

### LINKED ISSUE #23: (Requirejs) Using r.js to combine AMD files include isMobile.js throw error: Mismatched anonymous define() module: [object Object]
I'm not sure this is an issue or just my wrong.
At first, I include `isMobile.js` in my AMD project use the following code, it worked very well.
```javascript
require( [ "app", "isMobile" ], function(App, isMobile) {
    //...
});

```
But when I use `r.js` to optimize and combine my project and run again, the following error has occurred.
```
Mismatched anonymous define() module: [object Object]
```
Then I found  the description of this error [form the page of requirejs](http://requirejs.org/docs/errors.html#mismatch) .
So I think the problem may be in the line #105~106 of `isMobile.js`:
```javascript
 //AMD
define(global.isMobile = instantiate());
```
I tried to modify the code to look like this:
```javascript
//AMD
define( 'isMobile', [], global.isMobile = instantiate() );
```
Then it worked fine.

So I just submit this issue, and I'm not a veteran of the requirejs, anyone could give me some advice on this?

Btw, very nice project :).

### PR DESCRIPTION
**Pull request by mc-zone**
So I've submitted this PR to the issue #23 . Changed the line about AMD module define and add the module name (`isMobile`)  like this:
```javascript
//AMD
define('isMobile', [], global.isMobile = instantiate());
```

### CODE REVIEW

**Comment by kaimallea** [comment]
Nice! Also add yourself to contributors file and I'll merge it. :smiley:   Or I can add you myself if you don't want to.

**Comment by mc-zone** [comment]
Yes I've done. @kaimallea . Thanks! And I am honored.

**Comment by kaimallea** [comment]
:+1: Awesome, thank you for contributing!

**Pull request merged**
