### PR TITLE
docs: headings & webpack

### PR DESCRIPTION
**Pull request by zalog**
The first commit is just a minor glitch.
The second commit adds webpack import.

### CODE REVIEW

**Comment by zalog** [comment]
I just saw that we have another PR with that heading fix :)
Please let me know if you need to leave this with webpack only.

**Comment by kaimallea** [comment]
Fixed in #77

**Comment by zalog** [comment]
Ok, cool!
I can delete that commit and leave only our import line. It's ok like that?

**Comment by kaimallea** [comment]
@zalog after upgrading, that should do it! let me know if you have any issues!

**Comment by zalog** [comment]
Ok. There is another commit with webpack import.
Do we need that in readme file?
https://github.com/kaimallea/isMobile/pull/74/commits/16e41b0ee0a8341a1d5b1a6630d7a9dc78ac3b2b

I can keep this PR with that single commit.

**Pull request closed without merging**
