### PR TITLE
Add isMobile function to Browserify module.exports

### PR DESCRIPTION
**Pull request by bismarkhenao**
This allows to create a new object within events like onresize or orientationchange.

ES6
`import { isMobile } from 'ismobilejs'`

Then you can do thinks like 

js
```
let obj = isMobile();

window.onresize = () => {
  obj = isMobile();
}

window.addEventListener('orientationchange', () => {
  obj = isMobile();
}) 
```

_Right now, it's necessary to reload the complete page to get a new object._

### CODE REVIEW

**Comment by kaimallea** [comment]
Thanks for this and sorry for the delay! Can you remove the `dist` file? I want to have it generated with a commit to bump the version separately, after merging this. Thank you!

**Comment by bismarkhenao** [comment]
Done @kaimallea :)

**Comment by kaimallea** [comment]
🚀

**Pull request merged**
